const $=id=>document.getElementById(id);
let unit=0,index=0,playing=false,paused=false,sequential=false,played=0,epoch=0,timer=null,audio=null,pending=null;
function stop(){epoch++;clearTimeout(timer);pending=null;if(audio){audio.onended=null;audio.onerror=null;audio.pause();audio.src='';audio=null;}playing=false;paused=false;played=0;$('toggle').textContent='▶';}
function words(){return VOCAB[unit].words}
function render(){
 applyTheme(unit);
 $('units').innerHTML='';VOCAB.forEach((u,n)=>{const b=document.createElement('button');b.innerHTML=`<span>${String(n+1).padStart(2,'0')}</span>${u.name}`;b.className=n===unit?'active':'';b.setAttribute('aria-current',n===unit?'true':'false');b.onclick=()=>{stop();unit=n;index=0;render();$('current').textContent='选择一个单词';$('status').textContent='准备好就开始听吧'};$('units').append(b)});
 $('chapter').textContent=`CHAPTER ${String(unit+1).padStart(2,'0')}`;$('title').textContent=VOCAB[unit].name;$('count').textContent=`${words().length} 个词条 · 按书中分类`;
 $('words').innerHTML='';words().forEach((w,n)=>{const row=document.createElement('div');row.className='word';row.id='word-'+n;const num=document.createElement('span');num.className='number';num.textContent=String(n+1).padStart(2,'0');row.append(num);const b=document.createElement('button');b.className='wordname';b.textContent=w.word;b.onclick=()=>start(n,false);row.append(b);const p=document.createElement('span');p.className='page';p.textContent=`p. ${w.page}`;row.append(p);for(const [accent,label] of [['1','英音'],['2','美音']]){const v=document.createElement('button');v.className='voice';v.textContent='♪ '+label;v.setAttribute('aria-label',`${w.word} ${label}`);v.onclick=()=>{$('accent').value=accent;start(n,false)};row.append(v)}$('words').append(row)});$('position').textContent=`— / ${words().length}`;
}
function status(){const limit=Number($('repeat').value);$('status').textContent=`${$('accent').value==='1'?'英式':'美式'} · 第 ${played+1}${limit?' / '+limit:''} 次${paused?' · 已暂停':''}`;$('position').textContent=`${index+1} / ${words().length}`;}
function fail(message){stop();$('status').textContent=message;}
function start(n,seq){stop();if(!words().length)return;index=n;sequential=seq;playing=true;document.querySelectorAll('.word.selected').forEach(e=>e.classList.remove('selected'));$('word-'+index)?.classList.add('selected');$('current').textContent=words()[index].word;$('toggle').textContent='Ⅱ';play(epoch);}
function play(token){if(token!==epoch||!playing||paused)return;status();audio=new Audio(`https://dict.youdao.com/dictvoice?audio=${encodeURIComponent(words()[index].word)}&type=${$('accent').value}`);audio.playbackRate=Number($('rate').value);audio.onended=()=>{if(token!==epoch)return;played++;const max=Number($('repeat').value);if(max===0||played<max){pending=()=>play(token);timer=setTimeout(pending,Number($('gap').value));return}if(sequential&&(index<words().length-1||$('loop').checked)){pending=()=>{if(token===epoch)start((index+1)%words().length,true)};timer=setTimeout(pending,Number($('gap').value));return}stop();$('status').textContent='播放完成';};audio.onerror=()=>{if(token===epoch)fail('音频加载失败，请检查网络后重试')};audio.play().catch(e=>{if(token===epoch)fail(e.name==='NotAllowedError'?'请点击播放按钮继续':'音频暂不可用，请重试')});}
function toggle(){if(!playing){start(index,false);return}if(paused){paused=false;$('toggle').textContent='Ⅱ';if(audio&&!audio.ended){audio.play().catch(()=>fail('请重试播放'))}else if(pending){const action=pending;pending=null;action()}else play(epoch)}else{paused=true;clearTimeout(timer);audio?.pause();$('toggle').textContent='▶'}status();}
$('toggle').onclick=toggle;$('stop').onclick=()=>{stop();$('status').textContent='已停止'};$('prev').onclick=()=>start((index-1+words().length)%words().length,sequential);$('next').onclick=()=>start((index+1)%words().length,sequential);$('playAll').onclick=()=>start(0,true);
for(const id of ['accent','repeat','gap','rate'])$(id).onchange=()=>{if(playing)start(index,sequential)};
window.addEventListener('pagehide',stop);render();
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 try{Promise.resolve(document.modelContext.registerTool({name:'select_vocabulary_unit',description:'Switch to one of the 22 book units and display its words and theme. Stops current audio.',inputSchema:{type:'object',properties:{unit:{type:'integer',minimum:1,maximum:22}},required:['unit'],additionalProperties:false},execute(input){if(!input||!Number.isInteger(input.unit)||input.unit<1||input.unit>22)throw new Error('Unit must be an integer from 1 to 22');stop();unit=input.unit-1;index=0;render();$('current').textContent='选择一个单词';$('status').textContent='准备好就开始听吧';return {unit:unit+1,name:VOCAB[unit].name,wordCount:words().length}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
