const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),queue=new Map();let uid=0,audioInstances=0;
const prefix=fs.existsSync('dist/app.js')?'dist/':'';
function el(){return {value:'',textContent:'',children:[],attributes:{},set innerHTML(v){this.children=[]},get innerHTML(){return ''},checked:false,style:{setProperty(){}},dataset:{},classList:{add(){},remove(){}},setAttribute(k,v){this.attributes[k]=v},append(...items){this.children.push(...items)}}}
const document={getElementById(id){if(!elements.has(id))elements.set(id,el());return elements.get(id)},createElement:el,querySelector(){return el()},querySelectorAll(){return []},body:el(),documentElement:el()};
const ctx=vm.createContext({document,window:{addEventListener(){}},console,Audio:class{constructor(src){audioInstances++;this.src=src;this.ended=false}set src(value){this._src=value;this.ended=false}get src(){return this._src}play(){return Promise.resolve()}pause(){}},setTimeout(fn){const id=++uid;queue.set(id,fn);return id},clearTimeout(id){queue.delete(id)},applyTheme(){}});
vm.runInContext(fs.readFileSync(prefix+'words.js','utf8'),ctx);
for(const [id,value] of Object.entries({repeat:'3',gap:'1000',accent:'1',rate:'1'}))document.getElementById(id).value=value;
vm.runInContext(fs.readFileSync(prefix+'app.js','utf8'),ctx);
const run=s=>vm.runInContext(s,ctx),tick=()=>{const item=queue.entries().next().value;assert.ok(item,'scheduled playback');queue.delete(item[0]);item[1]()},end=()=>run('audio.ended=true;audio.onended()');
run('start(0,false)');for(let i=0;i<3;i++){end();if(i<2)tick()}assert.equal(run('playing'),false);assert.equal(queue.size,0);
document.getElementById('repeat').value='1';run('start(0,true)');end();run('toggle()');assert.equal(queue.size,0);run('toggle()');assert.equal(run('index'),1,'resume between words advances, no extra repetition');
run('start(0,true)');end();run('stop()');assert.equal(queue.size,0);assert.equal(run('playing'),false);
document.getElementById('repeat').value='0';run('start(0,false)');for(let i=0;i<7;i++){end();tick()}assert.equal(run('index'),0);assert.equal(run('playing'),true);run('stop()');
document.getElementById('repeat').value='1';document.getElementById('loop').checked=true;run('start(words().length-1,true)');end();tick();assert.equal(run('index'),0);run('stop()');
run('start(0,false);audio.onerror()');assert.equal(run('playing'),false);assert.match(document.getElementById('status').textContent,/加载失败/);
assert.equal(run('VOCAB.length'),22);assert.equal(run('VOCAB.reduce((s,u)=>s+u.words.length,0)'),3674);assert.equal(run('VOCAB[0].words.slice(0,6).map(w=>w.word).join(",")'),'atmosphere,hydrosphere,lithosphere,oxygen,oxide,carbon dioxide');
assert.equal(audioInstances,1,'all repetitions and words reuse the user-activated audio element');
console.log('PASS: repeat limits, infinite repeat, pause at boundary, cancellation, unit loop, errors, audio reuse, 22 units and first-page order');
const saved=new Map();ctx.localStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};
run('toggleFavorite(words()[0]);toggleFavorite(words()[2]);notebook=true;resetView()');
assert.equal(run('words().map(w=>w.word).join(",")'),'atmosphere,lithosphere');
assert.deepEqual(JSON.parse(saved.get('ielts-vocabulary.favorites.v1')),['0:0','0:2']);
run('start(0,true)');end();tick();assert.equal(run('words()[index].word'),'lithosphere');
run('toggleFavorite(words()[1])');assert.equal(run('playing'),false);assert.equal(run('words().length'),1);
run('toggleFavorite(words()[0])');assert.equal(run('words().length'),0);assert.equal(document.getElementById('playAll').disabled,true);
run('notebook=false;resetView()');
let row=document.getElementById('words').children[0],body=row.children[1],wordButton=body.children[0],meaning=row.children[2];
assert.equal(meaning.hidden,true);
document.getElementById('accent').value='2';wordButton.onclick({stopPropagation(){}});assert.equal(run('playing'),true);assert.equal(run('index'),0);assert.match(run('audio.src'),/type=2$/);assert.equal(meaning.hidden,true,'clicking a word plays without toggling the translation');run('stop()');
row.onclick({target:{closest:()=>null}});assert.equal(run('playing'),true,'clicking the row plays immediately');run('stop()');
row.onclick({target:{closest:()=>({})}});assert.equal(run('playing'),false,'controls do not bubble into row playback');
let meaningButton=row.children.find(e=>e.className==='meaning-toggle');meaningButton.onclick({stopPropagation(){}});assert.equal(meaning.hidden,false);meaningButton.onclick({stopPropagation(){}});assert.equal(meaning.hidden,true);assert.equal(run('playing'),false,'translation control never starts audio');
document.getElementById('showMeanings').checked=true;document.getElementById('showMeanings').onchange();
row=document.getElementById('words').children[0];body=row.children[1];assert.equal(row.children[2].hidden,false);row.children.find(e=>e.className==='meaning-toggle').onclick({stopPropagation(){}});assert.equal(row.children[2].hidden,true);
assert.equal(document.getElementById('words').children[1].children[2].hidden,false,'hiding one does not hide every translation');
ctx.localStorage.setItem=()=>{throw Error('storage denied')};run('toggleFavorite(words()[0])');assert.match(document.getElementById('storageNote').textContent,/本次/);
console.log('PASS: direct word/row playback, selected accent, independent translation controls, notebook ordering, persistence, sequential playback, removal during playback, empty controls, unavailable storage');
